//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad
    {
        public Especialidad()
        {
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int ID_Especialidad { get; set; }
        public string Nombre_Especialidad { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}
