//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int ID_factura { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public int ID_MetodoPago { get; set; }
        public string Articulo { get; set; }
        public double SubTotal { get; set; }
        public double Total { get; set; }
        public double Tax { get; set; }
        public System.DateTime Fecha { get; set; }
        public double PrecioTotal { get; set; }
    
        public virtual MetodoPago MetodoPago { get; set; }
    }
}
